version: '3.8'

services:
  mssql:
    platform: linux/arm64
    image: 'mcr.microsoft.com/mssql/server:2022-latest'
    container_name: 'mssql-2022'
    hostname: 'mssql-db'
    ports:
      - "1434:1433"
    environment:
      - MSSQL_SA_PASSWORD=Qwerty1234
      - ACCEPT_EULA=Y
    user: root
    volumes:
      - ./mssql-2022-data:/var/opt/mssql