version: '3'

services:
  mssql:
    platform: linux/arm64
    image: 'mcr.microsoft.com/azure-sql-edge:latest'
    cap_add: [ 'SYS_PTRACE' ]
    container_name: 'mssql'
    ports:
      - '1433:1433'
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Qwerty1234
    user: root
    volumes:
      - 'mssql-azuresql-edge-data:/var/opt/mssql'

volumes:
  mssql-azuresql-edge-data:
